<input name="merchantId"    type="hidden"  value="{{$merchantId}}" />
<input name="accountId"     type="hidden"  value="{{$merchantId}}" />
<input name="description"   type="hidden"  value="{{$description}}" />
<input name="referenceCode" type="hidden"  value="{{$referenceCode}}" />
<input name="amount"        type="hidden"  value="{{$amount}}" />
<input name="tax"           type="hidden"  value="{{$tax}}"  >
<input name="taxReturnBase" type="hidden"  value="{{$taxReturnBase}}" >
<input name="currency"      type="hidden"  value="{{$currency}}" >
<input name="signature"     type="hidden"  value="{{$signature}}"  >
<input name="test"          type="hidden"  value="{{$isTest}}" >
<input name="buyerEmail"    type="hidden"  value="{{$buyerEmail}}" >
<input name="responseUrl"    type="hidden"  value="{{$responseUrl}}" >
<input name="confirmationUrl"    type="hidden"  value="{{$confirmationUrl}}" >